### ISSUE TITLE
GoMap!/OsmAnd tasks

### ISSUE THREAD

**Issue by tohaklim** [Zverik/osmstreak#1]
Thanks for some gamification of OSM, Zverik! Very timely, seeing how even GMaps are rolling out badges for LGs.
Seeing how there are Maps.me and StreetCompl tasks, may I suggest GoMap (iOS only) and OsmAnd (Android only)?
For any suggestions on tasks, would you want a pull or an issue?

**Comment by Zverik** [comment]
If you have the time, please do pull requests — you can see examples for tasks in the `tasks` directory. Or just write them here, I'll do these eventually :)

**Comment by tohaklim** [comment]
Cool, I am hoping to contribute on the weekend. Any particular emoji library you use?

**Comment by Zverik** [comment]
No, I just go to [emojipedia](https://emojipedia.org/) and copy a character that seems relevant. Every user sees different emojis, depending on their operating system and browser :)

**Comment by Zverik** [comment]
Done in 031dae6ba5848bbba9bde3009040bb8ab7635456
