### ISSUE TITLE
Опечатка в enourmous -> enormous

### ISSUE THREAD

**Issue by alexander-ii** [Zverik/osmstreak#14]
Let's create a changeset with an **enourmous** bounding box. Map something first in [https://www.openstreetmap.org/#map=5/-48.487/-69.895 South Chile], and then in [https://www.openstreetmap.org/#map=6/55.912/159.335 Kamchatka].

**Comment by tohaklim** [comment]
Wow, that's a task? First the fix, now this, I feel like Zverik just wants to troll some people 😄

**Comment by Zverik** [comment]
I absolutely love trolling people :)
Thanks @govvin for the fix.
