### ISSUE TITLE
Опечатка natural=tree_node -> natural=tree node

### ISSUE THREAD

**Issue by alexander-ii** [Zverik/osmstreak#15]
Mapping a tree is not just placing a **''natural=tree_node''**. You have to specify its type. Please read wiki pages on [https://wiki.openstreetmap.org/wiki/Key:leaf_type leaf_type] and [https://wiki.openstreetmap.org/wiki/Key:leaf_cycle leaf_cycle], and then add 2 trees near your home or somewhere familiar to you using these tags.

**Comment by Zverik** [comment]
Thanks for noticing! Fixed in 60ff95f88c0f97d874698d0ade7f088f2440a063
