### ISSUE TITLE
Add Github ribbon and link to transifex

### ISSUE THREAD

**Issue by don-vip** [Zverik/osmstreak#16]
Can you please add on the website a [Github ribbon](https://github.com/blog/273-github-ribbons) and a link to the translation platform? I spotted a mistake in French translation but it's currently hard to find how to fix it.

**Comment by Zverik** [comment]
I don't like the ribbon, since it is too prominent and distracts from the website. But the links certainly should be on the website, most likely on the "About" page. I will do that, thanks.

**Comment by Binnette** [comment]
There is a link to this repo in the "about" page: http://streak.osmz.ru/about
(so no need to add the ribbon)

With PR #45, there is now a link in the readme of this repo to the translation platform.

So, we can now close this issue 👍
