### ISSUE TITLE
Reword the streams task

### ISSUE THREAD

**Issue by Zverik** [Zverik/osmstreak#24]
> Yeah, indeed. I unterstand that in this task you should map some streams. But in the context of "rivers are mostly mapped" you could say, that streams aren't mapped at all, right? And for my unterstanding it should be "..., but streams aren't (mapped) too many", or "..., but streams there are too many unmapped".

https://www.transifex.com/openstreetmap/osm-streak/translate/#ru/$/126626975?issue=yes

**Comment by tohaklim** [comment]
issue just with RU translation?
EN version could be reworded like "Rivers are mostly mapped all over the world, _but many streams remain unmapped / streams are too numerous to map all of them_. Choose any, and map it. Not a river — a stream."
