### ISSUE TITLE
Link to the forge in the app

### ISSUE THREAD

**Issue by tuxayo** [Zverik/osmstreak#32]
I struggled a bit to find this issue tracker. And telling that this app is libre/open source would be great, don't hide it ;)
(well there is no license so is "All Right Reserved" by default)

It could also give you credit and discover your other great projects. (Also link to http://osmz.ru/ ?)

Thanks for this great motivational tool :)

**Comment by tuxayo** [comment]
Related: It's not linked in http://osmz.ru/ so people might miss OSM Streak when looking at your outstanding list of projects.

**Comment by Binnette** [comment]
License problem solved by PR #44.
Also, there is a direct link to the repo in "about" page: http://streak.osmz.ru/about

:+1: for a link to OSM Streak in page http://osmz.ru/
