### ISSUE TITLE
Telegram message in English?

### ISSUE THREAD

**Issue by nyampire** [Zverik/osmstreak#35]
I found following text in Telegram message.
But if the translated messages are merged, they are not in English.

`I will write to you in English.`

This is set as `lang_set`, so around here?
https://github.com/Zverik/osmstreak/blob/master/telegram.py#L138

**Comment by Zverik** [comment]
Try sending `/lang ja` to the bot:
```
Ilya Zverev, [23.02.18 10:32]
/lang ja

OSM Streak, [23.02.18 10:32]
メッセージは英語で送られます。
```
When you don't specify a language, you'll get a list of options. I think this affects the website as well.
