### ISSUE TITLE
Update i18n and missing strings in transifex

### ISSUE THREAD

**Issue by Binnette** [Zverik/osmstreak#43]
Hi thanks a lot for this web app, it is very funny to use.

I just finished to review/translate all strings for french. Can you please, publish them to your web site ?

Also, some strings are missing in transifex : contribute & contribute_content. Can you add them in transifex ? That way, we will be able to translate them.

**Comment by Zverik** [comment]
Hi, and thanks for translating! I've just pushed your translations to the website, and updated the strings, so you might see the missing ones.
