### ISSUE TITLE
Hungarian translation ready

### ISSUE THREAD

**Issue by debyos** [Zverik/osmstreak#52]
Dear Zverik,

I have translated OSM Streak [into Hungarian](https://www.transifex.com/openstreetmap/osm-streak/language/hu/), you could [put it online](https://github.com/Zverik/osmstreak/tree/master/lang). (Task descriptions are still missing but I think the whole thing is usable even without them. I will translate them later on.)
Thanks

Gábor

**Comment by Zverik** [comment]
Thank you, I did.
