### ISSUE TITLE
The lit map from my today's task is no longer available 

### ISSUE THREAD

**Issue by Jakuje** [Zverik/osmstreak#55]
There are some suggested alternative on the website, but I do not know how the original looked like. It would be great to select a new map for visualization of the changes

https://github.com/Zverik/osmstreak/blob/72d424fafc131f3ec57dc4ed98e0343ed970d4f9/tasks/2_lit.yaml#L5

**Comment by cincodenada** [comment]
I couldn't find a new map - I opened PR #57 to remove the link for now.
