### ISSUE TITLE
Persian translation complete

### ISSUE THREAD

**Issue by DearRude** [Zverik/osmstreak#71]
OSM Streak translation in Persian (Farsi) has been completed.
Any plans for deploying it?

**Comment by Zverik** [comment]
Thank you! Just updated the website and the Telegram bot :)

**Comment by ARADesigner** [comment]
Hello . I thank your team (osmstreak). The Persian translation had a number of minor problems that have now been corrected and are now complete. Please update Persian language.
Thanks.
